name: as_toast_x

description: 'A beautiful designed toast with animations, contains multiple built in designs and let you design your toast'
version: 1.1.1

homepage: https://github.com/asseries/as_toast_x
issue_tracker: https://github.com/asseries/as_toast_x/issues

#screenshots:
#  - description: 'Demo'
#    path: screenshots/toast.gif



environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '>=3.7.9'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
